"""add_resume_nlp_fields

Revision ID: 888ab0f2804f
Revises: af0119d9595e
Create Date: 2026-09-13 13:01:33.570465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888ab0f2804f'
down_revision: Union[str, Sequence[str], None] = 'af0119d9595e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('raw_text', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('extraction_status', sa.String(length=50), nullable=False))
    op.add_column('resumes', sa.Column('audit_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'audit_json')
    op.drop_column('resumes', 'extraction_status')
    op.drop_column('resumes', 'raw_text')
    # ### end Alembic commands ###
