"""add_job_matching_nlp_fields

Revision ID: dfca128d3130
Revises: 888ab0f2804f
Create Date: 2026-09-13 13:56:35.476365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfca128d3130'
down_revision: Union[str, Sequence[str], None] = '888ab0f2804f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('missing_required_skills', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('missing_preferred_skills', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('weak_skills', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('scoring_breakdown_json', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('matcher_version', sa.String(length=20), nullable=False))
    op.add_column('job_matches', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('jobs', sa.Column('preferred_skills', sa.String(length=500), nullable=True))
    op.add_column('jobs', sa.Column('education_requirement', sa.String(length=255), nullable=True))
    op.add_column('skill_gaps', sa.Column('why_it_matters', sa.Text(), nullable=True))
    op.add_column('skill_gaps', sa.Column('roadmap_topics_json', sa.Text(), nullable=True))
    op.add_column('skill_gaps', sa.Column('suggested_practice', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gaps', 'suggested_practice')
    op.drop_column('skill_gaps', 'roadmap_topics_json')
    op.drop_column('skill_gaps', 'why_it_matters')
    op.drop_column('jobs', 'education_requirement')
    op.drop_column('jobs', 'preferred_skills')
    op.drop_column('job_matches', 'updated_at')
    op.drop_column('job_matches', 'matcher_version')
    op.drop_column('job_matches', 'scoring_breakdown_json')
    op.drop_column('job_matches', 'weak_skills')
    op.drop_column('job_matches', 'missing_preferred_skills')
    op.drop_column('job_matches', 'missing_required_skills')
    # ### end Alembic commands ###
