"""add_job_provider_and_otp_tables

Revision ID: ead46dfb13be
Revises: b6a47dde9741
Create Date: 2026-09-14 11:27:11.528000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead46dfb13be'
down_revision: Union[str, Sequence[str], None] = 'b6a47dde9741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.create_index(op.f('ix_email_otps_id'), 'email_otps', ['id'], unique=False)
    op.add_column('jobs', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('jobs', sa.Column('application_url', sa.String(length=500), nullable=True))
    op.add_column('jobs', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_column('jobs', 'external_id')
    op.drop_column('jobs', 'application_url')
    op.drop_column('jobs', 'source_url')
    op.drop_column('jobs', 'source')
    op.drop_index(op.f('ix_email_otps_id'), table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.drop_table('email_otps')
    # ### end Alembic commands ###
